### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/my-creative-gems#1]
As a user, I want to **register for an account** so that I can **post text and media content.**

## Acceptance Criteria
1. A form to sign up
2. A form to login
3. A button to logout

## Tasks
- [ ] Create signup form
- [ ] Create login form
- [ ] Create logout button
