### ISSUE TITLE
Registration form includes rules checkbox

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/my-creative-gems#3]
As a user, I want to **register for an account** so that I can **like, follow or commenting users profiles or posts**

## Acceptance Criteria
1. Checkbox in form to accept general rules for commenting

## Tasks
- [ ] Add required checkbox "I have read and understand the rules for commenting"
- [ ] Add link to modal "Rules for commenting"
- [ ] Create modal with rules for commenting
